### PR TITLE
31 fix ice

### LINKED ISSUE #31: Fix technology aliases - ICE
Right now the palette doesn't recognise "ICE" written with capitals and returns "ice" label as "ICE" which is incorrect. Fix

### PR DESCRIPTION
**Pull request by MonikaFu**
Closes #31 

In this PR I fix the `scale_*` functions so that they work with data other than lower case strings.

Additionally, I add a `labels` parameter so that user can use their own labels if they don't like the pretty labels that are default. 

I also make the labels even prettier by spelling out technologies.

### CODE REVIEW

File: R/scale_colour_2dii.R [hunk 1]
```diff
@@ -3,10 +3,14 @@
...
+#'   specified then the general 2dii scale is used
 #' @param colour_groups A vector containing groups variable to which colours are
-#'  assigned. It is needed when the data assigned to `colour` aesthetic are not
-#'  all contained in colour aliases of the palette.
+#'   assigned. It is needed when the data assigned to `colour` aesthetic are not
+#'   all contained in colour aliases of the palette. By default it is null and
+#'   then only names in data that are also found in colour aliases for the
+#'   palette are coloured.
+#' @param labels Labels parameter to be used in `ggplot2::scale_colour_manual`.
+#'   By default it is set to an internal function beatifying the labels.
```
Comment (maurolepore) [inline R/scale_colour_2dii.R:13]: Fix type: `bea{+u+}tifying`

File: R/scale_colour_2dii.R [hunk 2]
```diff
@@ -47,13 +51,19 @@
...
 scale_colour_2dii <- function(
                               palette = c("2dii", "1in1000", "pacta"),
-                              colour_groups = NULL, ...) {
+                              colour_groups = NULL,
+                              labels = NULL,
+                              ...) {
   colour_aliases <- get_colour_aliases(palette, colour_groups)
 
+  if (is.null(labels)) {
+    labels = as_function(~ make_pretty_labels(.x))
```
Comment (maurolepore) [inline R/scale_colour_2dii.R:60]: You may write this as 

```r
labels <- labels %||% as_function(~ make_pretty_labels(.x)) 
```

File: R/scale_colour_2dii.R [hunk 3]
```diff
@@ -64,13 +74,19 @@ scale_color_2dii <- scale_colour_2dii
 #' @export
 scale_fill_2dii <- function(
                             palette = c("2dii", "1in1000", "pacta"),
-                            colour_groups = NULL, ...) {
+                            colour_groups = NULL,
+                            labels = NULL,
+                            ...) {
```
Comment (maurolepore) [inline R/scale_colour_2dii.R:79]: Style active file (shift + ctrl + P)

File: R/utils-tests.R [hunk 4]
```diff
@@ -32,3 +32,13 @@ example_plot_scale_fill <- function() {
...
+
+example_data_lowercase <- function() {
+  tibble::tibble(x=rep(1:5, 3), val=sample(1:100, 15),
+                   variable=rep(c("ice", "electric", "hybrid"), 5))
+}
+
+example_data_uppercase <- function() {
+  tibble::tibble(x=rep(1:5, 3), val=sample(1:100, 15),
+                   variable = rep(c("ICE", "Electric", "Hybrid"), 5))
+}
```
Comment (maurolepore) [inline R/utils-tests.R:44]: Style.

File: R/utils.R [hunk 5]
```diff
@@ -19,28 +19,40 @@ deparse_1 <- function(expr, collapse = " ", width.cutoff = 500L, ...) {
...
-        x = glue("Number of unique colours in the palette: {length(available_colours)}.
-                 You passed a column with {length(names)} distinct values."),
-        i = "Consider splitting over multiple plots."
+  names_lower <- unique(tolower(names))
+  missing_names_core <- setdiff(names_lower, names(colour_aliases))
+  missing_names_lettercase <- setdiff(names, names(colour_aliases))
+  if (length(missing_names_core) < length(missing_names_lettercase)) {
+    names_case_difference <- setdiff(missing_names_lettercase, missing_names_core)
+    aliases_case_difference <- c()
+    for (i in 1:length(names_case_difference)) {
```
Comment (maurolepore) [inline R/utils.R:30]: `1:lengh(x)` is dangerous. When `x` has length 0 the result isn't what you expect:

``` r
x <- character(0)
1:length(x)
#> [1] 1 0
```

<sup>Created on 2022-03-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Instead use with `seq_along(x)`. You may run `goodpractice::gp()` to detect more instances of this.

File: tests/testthat/test-scale_colour_2dii.R [hunk 6]
```diff
@@ -100,3 +98,53 @@ test_that("warns about assigning colours", {
...
+  expect_true(identical(g$plot$scales$scales[[1]]$labels, new_labels))
+})
+
+test_that("scale_*_colour works with different letter cases", {
+  p1 <- ggplot2::ggplot(example_data_lowercase(), ggplot2::aes(x = x, y = val)) +
+    ggplot2::geom_line(ggplot2::aes(colour = variable)) +
+    scale_colour_2dii(palette = "pacta", colour_groups = example_data_lowercase()$variable)
+
+  p2 <- ggplot2::ggplot(example_data_uppercase(), ggplot2::aes(x = x, y = val)) +
+    ggplot2::geom_line(ggplot2::aes(colour = variable)) +
```
Comment (maurolepore) [inline tests/testthat/test-scale_colour_2dii.R:128]: The calls to `ggplot2::` take a lot of screen real state. I think they obscure the actually interesting code 
:-(

**Review by maurolepore — APPROVED** [review]
LGTM

File: tests/testthat/test-scale_colour_2dii.R (hunk 6 above)
Comment (MonikaFu) [reply tests/testthat/test-scale_colour_2dii.R:128]: I agree. It was required because I didn't have those functions in the `imports`. I left some calls to `ggplot2::` but added `ggplot` and `aes` to imports.

**Comment by MonikaFu** [comment]
Thank you @maurolepore for your comments! I addressed most of them and merging the PR now 💯
